### ISSUE TITLE
[Quest] Cumplir con tu deber

### ISSUE THREAD

**Issue by GastonCK** [andeswow/bugtracker#1]
### ¿En qué cliente juegas?

enUS

### Facción

Alianza

### Describe el problema

Al tomar la quest https://www.wowhead.com/wotlk/es/quest=12227/cumplir-con-tu-deber y luego clickear la opción "Use the outhouse" te entrega la semilla instantáneamente sin que pase nada. También se puede observar que hay un Imp dentro del baño que no debería estar ahí.
![WoWScrnShot_080923_112327](https://github.com/andeswow/bugtracker/assets/65800273/d03c6665-f1e6-4f9c-936a-cced2e5c2bdb)
![WoWScrnShot_080923_112037](https://github.com/andeswow/bugtracker/assets/65800273/2ea871ea-f177-41ba-bc30-4dead3af8e9a)

### Comportamiento esperado

Al hacer click en "Use the outhouse" el personaje debería ingresar al baño y empezar a defecar y gritar. Durante la duración de este evento el personaje debería tener el debuff ["Indisposed" ](https://www.wowhead.com/wotlk/spell=53017/indisposed) y al finalizar la duración del debuff se entregaría la [semilla necesaria ](https://www.wowhead.com/wotlk/item=37250/partially-processed-amberseeds)
Video de Wrath Classic https://www.youtube.com/watch?v=_a5TgN7owJ4
También observamos en el video que no hay ningún Imp dentro del baño.

### Pasos para reproducir el problema

1. Tomar la quest https://www.wowhead.com/wotlk/quest=12227/doing-your-duty
2. Acercarse al baño y hacerle click
3. Click en la opción Use the outhouse
4. Recibe la semilla instantáneamente sin realizar el evento mostrado en el video.
5. Observa que hay un Imp dentro del baño

### Sistema Operativo

Debian 11

### Módulos

- [mod-aoe-loot](https://github.com/azerothcore/mod-aoe-loot)
- [mod-recruit-friend](https://github.com/pangolp/mod-recruit-friend)
- [mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
- [mod-npc-promotion](https://github.com/pangolp/mod-npc-promotion)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-quest-loot-party](https://github.com/pangolp/mod-quest-loot-party)

### Nombre del servidor

AndesWOW

**Comment by pangolp** [comment]
Algunas cosas interesante sobre este tipo de misiones, que también son importantes a la hora de reportar y que de ser necesario, y se confirman, nosotros vamos a tratar de añadir al principio, es que te pueden pedir la forma de llegar al npc. Eso se hace con el comando `.go c` y para eso, necesitas saber cual es el entry del npc que te da la quest. En el caso de los gossip, generalmente, están acompañados de condicionales, las quest, solo deben estar disponibles, en el caso de que el jugador, tenga la quest tomada y no completada, porque muchas veces se muestran de todos modos, aunque el mismo no la tenga, y desencadenan que se ejecute un evento, que no debería de suceder. Tomare fotos, y adjuntare dicha información.

- Con `list c 27277` tendríamos toda la lista de NPC que tiene ese entry.
- Con `.go c 108840` vamos directamente hasta el NPC.
- Con `.quest add 12227` nos añadimos la quest.

![WoWScrnShot_080923_161949](https://github.com/andeswow/bugtracker/assets/2810187/0c0773f8-97d2-432e-adf7-9075007f1c06)

![WoWScrnShot_080923_162116](https://github.com/andeswow/bugtracker/assets/2810187/1f21728d-66cf-463f-b67f-1c1b9fbf6cb6)
