### ISSUE TITLE
[Recruit a friend] Fallo al usar el recruit view

### ISSUE THREAD

**Issue by pangolp** [andeswow/bugtracker#2]
### ¿En qué cliente juegas?

esES

### Facción

Ambas

### Describe el problema

Actualmente, al usar el comando, aparece en el chat información equivocada.
Como se puede apreciar en la foto.

![WoWScrnShot_080923_162023](https://github.com/andeswow/bugtracker/assets/2810187/f1823510-06dc-4938-b5ba-b402a4960415)

![WoWScrnShot_080923_162026](https://github.com/andeswow/bugtracker/assets/2810187/2ae7dfd4-ecf5-456c-937b-b58fa32ac63a)

![WoWScrnShot_080923_161931](https://github.com/andeswow/bugtracker/assets/2810187/3de6f296-18dd-448e-8bc7-b2e24a3eab6c)

![WoWScrnShot_080923_161927](https://github.com/andeswow/bugtracker/assets/2810187/1b76a1ed-8f7e-4cdb-825b-7fb4bedc6d98)

### Comportamiento esperado

Al usar el `.recruit view` debería de poder visualizar los nombres de los personajes de mi reclutado.
Y no debería de presentar fallos, al reclutar.

### Pasos para reproducir el problema

1. Crearse una cuenta en el servidor
2. Intentar reclutar a un amigo con el comando `.recruit add`
3. También se puede visualizar, al usar el comando `.recruit view`

### Sistema Operativo

Debian 11

### Modulos

- [mod-aoe-loot](https://github.com/azerothcore/mod-aoe-loot)
- [mod-recruit-friend](https://github.com/pangolp/mod-recruit-friend)
- [mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
- [mod-npc-promotion](https://github.com/pangolp/mod-npc-promotion)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-quest-loot-party](https://github.com/pangolp/mod-quest-loot-party)

### Nombre del servidor

AndesWOW

**Comment by crystsennin** [comment]
esES

**Comment by pangolp** [comment]
> esES

Lo añadí al principio del reporte.
