### ISSUE TITLE
Puedo atacar a los npc a traves de los obstáculos

### ISSUE THREAD

**Issue by doom970118** [andeswow/bugtracker#3]
### ¿En qué cliente juegas?

esES

### Facción

Horda

### Describe el problema

El problema es que puedo atacar a los npc a través de los obstáculos.
![Obstaculo 1](https://github.com/andeswow/bugtracker/assets/107557992/9ebcc9fe-a0a3-4234-bdc6-09d1f7c65837)
![Obstaculo 2](https://github.com/andeswow/bugtracker/assets/107557992/4ee6aed0-563f-44de-91ad-c40e559d234c)

### Comportamiento esperado

Normalmente cuando marco un npc pero delante de mi se encuentran obstáculos no deberia dejarme poder atacarle o castear cualquier cosa.

### Pasos para reproducir el problema

1. Busca un npc que se encuentra detrás de un obstáculo
2. Selecciona ese npc y luego casteale algo o atácalo
3. Veras como puedes atacar al npc detrás del obstáculo

### Sistema Operativo

Debian 11

### Modulos

- [mod-aoe-loot](https://github.com/azerothcore/mod-aoe-loot)
- [mod-recruit-friend](https://github.com/pangolp/mod-recruit-friend)
- [mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
- [mod-npc-promotion](https://github.com/pangolp/mod-npc-promotion)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-quest-loot-party](https://github.com/pangolp/mod-quest-loot-party)

### Nombre del servidor

AndesWOW

**Comment by GastonCK** [comment]
Muchas gracias por el reporte!
Necesitariamos que nos ayudes a investigar si esas piedras realmente deberian impedir los ataques a distancia, se que puede sonar obvio que si pero en realidad no es tan obvio como parece. 
Si te pones a levelear en el Classic Era o el Classic Wotlk te encontraras con miles y miles de texturas en el terreno (como las piedras de tus fotos) que NO impiden los ataques a distancia.
Personalmente recuerdo que fue una experiencia bastante decepcionante haber jugado el Wotlk Classic y una de las razones de mi decepción era que se podia atacar a distancia a traves de un monton de arboles, piedras y texturas.
También si buscas en google "wow classic Line of Sight" encontraras muchas discusiones de foros y quejas sobre este tema, lo cual confirma que a pesar de que parece bug, en realidad esta hecho así aproposito (blizzlike)

Dejo el tema abierto y estaré investigando un poco mas sobre esto, cualquier persona que pueda aportar informacion y ejemplos reales de como debería funcionar ayudaria muchisimo

**Comment by doom970118** [comment]
Acabo de revisar en el servidor Warmane y si funciona correctamente el obstáculo.
![Obstaculo 1 Correcto](https://github.com/andeswow/bugtracker/assets/107557992/238b9380-7e33-4e43-9044-4a3c94ecdb27)
![Obstaculo 2 Correcto](https://github.com/andeswow/bugtracker/assets/107557992/7b3cbef4-5e03-448f-80ac-7626f2fa7b9a)
Si observas las capturas en la primera vez al npc del otro lado de la roca y cuando miras la segunda captura intento atacar al npc y no sucede, me sigo manteniendo fuera de combate aun presione varias veces atacar al npc.

**Comment by GastonCK** [comment]
Para investigar como deberia funcionar necesitamos buscar en fuentes confiables, lo ideal serian videos/comentarios del viejo Wotlk o del actual Wotlk Classic de Blizzard. Si buscamos en proyectos de servers privados deberían ser proyectos que tengan una estricta filosifia "blizzlike" de trabajo y cuyo código sea público.
No podemos considerar a Warmane como fuente confiable debido a que trabajan de manera cerrada desde hace mas de una decada y nadie puede acceder a mirar los cambios que realizan en el codigo para confirmar si usan fuentes blizzlike o si son a criterio personal de su equipo de trabajo.

Revolviendo un poco en antiguos reportes de Azerothcore y Trinitycore que sean similares al tuyo:
https://github.com/azerothcore/azerothcore-wotlk/issues/4911
https://github.com/TrinityCore/TrinityCore/issues/25654
https://github.com/azerothcore/azerothcore-wotlk/issues/11234
Encontramos que la mayoria de estos casos de ataques a distancia a traves de determinados obstaculos son lamentablemente Blizzlike, por ende correctos.

Con esto no puedo confirmar que el caso particular expuesto en este reporte no sea bug pero trato de enfatizar la importancia de encontrar una fuente confiable. No por capricho nuestro sino porque tanto Azerothcore como Trinitycore nos rechazarian el reporte por falta de pruebas fiables.

**Comment by doom970118** [comment]
Eso en un error sea o no blizzlike, y aun que sea un comportamiento blizzlike no quiere decir que sea correcto ese comportamiento. Deberia de ser arreglado como hizo Warmane ya que como mismo yo puedo atacar a un npc a través de un obstáculo el npc puede atacarme a mi si tiene la posiblidad de atacar a distancia y eso sea blizzlike o no afecta la experiencia de juego. En mi opinión, con que sea blizzlike no quiere decir que se deba de dejar ese error ya que es un error y deberia de ser arreglado.

**Comment by pangolp** [comment]
Lamentablemente, no pasa por lo que queremos, si no, por lo que se construye a nivel comunidad. AzerothCore es Blizzlike. Sin embargo, si más adelante, alguien realiza un arreglo, aunque sea custom, lo evaluaremos y veremos si la comunidad lo quiere introducir o no. Lamentablemente, los servidores como Warmane, no aportan el código público, así que quedamos a la espera de ver que puede hacer la comunidad o nosotros como miembros de ella. Pero si es Blizzlike, del lado de la comunidad, no creo que lo modifiquen y yo por ahora, en tema de mapeos, no me he metido. Ando en tema de scripts, spells, módulos y ese tipo de cosas. No te voy a mentir. Si se consigue algo, se prueba, se evalua y luego vemos. Pero lamentablemente por ahora, el contenido del servidor es Blizzlike con módulos custom. Ya veremos más adelante. Si queres, lo podes evaluar en AzerothCore con un informe igual que este pero en inglés y seguramente te van a dar o no, una respuesta parecida a la que te dio @GastonCK . Ya veremos

**Comment by doom970118** [comment]
Estoy más que seguro que ningún jugador de world of warcraft quiere atacar o que sea atacado a través de un obstáculo.

**Comment by pangolp** [comment]
Yo no lo puedo arreglar hoy. Y si no es Blizzlike, AzerothCore posiblemente nunca lo cambie, a menos que sea con un módulo. No es lo que queremos. Es lo que tenemos. Ahora si Warmane quiere compartir el código, con gusto lo pruebo y lo analizamos / probamos. PD. Nunca pasó, y dudo que pase. Así que hay que ser realistas, somos una comunidad, no una empresa. Sin embargo, si aparece algo, llegado el momento, lo probaremos.

**Comment by pangolp** [comment]
Lamento la tardanza, pero acabo de proponerle a la comunidad una posible solución al problema.
Actualmente, tenemos un proyecto en curso, les dejo el enlace de la comunidad, por si se quieren unir.
https://discord.gg/CunsDBu8YK

**Comment by GastonCK** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/18816
