### ISSUE TITLE
[ICC] Sindragosa no respawnea en rearme de ID

### ISSUE THREAD

**Issue by GastonCK** [andeswow/bugtracker#5]
### ¿En qué cliente juegas?

enUS

### Facción

Ambas

### Describe el problema

Sindragosa no respawnea cuando se rearma el ID al dia siguiente de haber wipeado y tirado raid off.
Ya hay un reporte abierto sobre esto: https://github.com/azerothcore/azerothcore-wotlk/issues/16751

### Comportamiento esperado

Sindragosa siempre deberia respawnear

### Pasos para reproducir el problema

Wipe en Sindragosa
Raid off
Rearme del ID otro dia
Ir a la sala de Sindra y verificar que no aparece

### Sistema Operativo

Debian 11

### Modulos

- [mod-aoe-loot](https://github.com/azerothcore/mod-aoe-loot)
- [mod-recruit-friend](https://github.com/pangolp/mod-recruit-friend)
- [mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
- [mod-npc-promotion](https://github.com/pangolp/mod-npc-promotion)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-quest-loot-party](https://github.com/pangolp/mod-quest-loot-party)

### Nombre del servidor

AndesWOW

**Comment by Fireevil** [comment]
Confirm in last rev https://github.com/azerothcore/azerothcore-wotlk/commit/23c5e990b6b6fe9dbc8fff1f2df5f3da9bc557e1 
also after restarting server the sindragosa it does not appear

**Comment by pangolp** [comment]
> Confirm in last rev [azerothcore/azerothcore-wotlk@23c5e99](https://github.com/azerothcore/azerothcore-wotlk/commit/23c5e990b6b6fe9dbc8fff1f2df5f3da9bc557e1) also after restarting server the sindragosa it does not appear

Hello, this is a bugtracker in Spanish. Here we discuss the themes, test them, and upload them to the AzerothCore repository, if confirmed. Your confirmation may be useful within the community issue. Here the debates, we try to make them in Spanish. Thank you. https://github.com/azerothcore/azerothcore-wotlk/issues/16751

**Comment by Fireevil** [comment]
Es la costumbre uno rara vez ve cosas en español jaja yo también programo pero pues no había visto que también tenían apartado en español mejor para mi

**Comment by pangolp** [comment]
Este bugtracker lo armamos para un servidor que estamos por crear en Argentina para Sudamérica (por temas de ping). Aunque si el ping no les molesta, pueden jugar de donde quieran. La idea es detectar y escalar fallos. Y en caso de que yo pueda repararlos, subir el issue y el pull request correspondiente. Así que acá recibimos fallos de la gente del servidor, los debatimos y los subimos al repositorio de AzerothCore en caso de que se confirme.

**Comment by GastonCK** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/18179
